### ISSUE TITLE
Default exports are broken?

### ISSUE THREAD

**Issue by ianrtracey** [americanexpress/parrot#8]
When `parrot-middleware`  is being used with Typescript, the default import statement for `parrot-middleware` fails: 
```javascript
import parrot from 'parrot-middleware'
```
```bash
TypeError: parrot_middleware_1.default is not a function
```

It seems as though the problem may be with how the default package is being exported here:
https://unpkg.com/parrot-middleware@3.1.0/lib/index.js.

The following line:
```javascript
module.exports = exports['default'];
```
may be causing issues because `module.exports` is expecting something with the following shape for default exports:
```javascript
module.exports = { default: ... }
```

The workaround is currently:
```javascript
import * as parrot from 'parrot-middleware'
```

**Comment by crosscompile** [comment]
I think this is due [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports) being used in parrot-middleware's build step.  That plugin enables parrot-middleware to be used in Node without the `default` property:
```js
const parrot = require('parrot-middleware');

// intead of

const parrot = require('parrot-middleware').default;
```
For your TypeScript build, can you try compiling with `esModuleInterop` set to `true`?  I think this issue is [part of the reason the flag was added](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop).
